### PR TITLE
Add test that specs out multi-user return behavior

### PR DESCRIPTION
**Pull request by claudijd**
This is a unit-test addition to verify the behavior of what would happen if we had two users with the same name.

### CODE REVIEW

**Comment by willkg** [comment]
This adds a test for a situation that can't happen due to db constraints--you can't have two users with the same username.

**Comment by claudijd** [comment]
@willkg yes, I was just realizing that, sort of trial by fire on this one.  The failure behavior is expected, so I'm closing this PR.

**Comment by willkg** [comment]
No worries! I apologize for being overly curt.

I haven't checked, but it'd be good if we had a test for what happens when two users have the same email address--that's the thing we're using to connect an OIDC identity with a Django identity. That's similar to this and maybe what you were trying to get at. Does that sound right?

**Comment by claudijd** [comment]
@willkg yes, that is what I was trying to test.  I will probably send a PR for that soon.  It seems to be a decent testing strategy, assuming I'm not spamming you guys too much.

**Comment by claudijd** [comment]
FWIW, I checked and a test for this does exist...

https://github.com/mozilla/mozilla-django-oidc/blob/master/tests/test_auth.py#L388-L411

**Pull request closed without merging**
