### PR TITLE
Fix #266: Update `is_safe_url` call for Django 2.1

### LINKED ISSUE #266: is_safe_url() got an unexpected keyword argument 'host' (Django 2.1)
In the [Django deprecation timeline](https://docs.djangoproject.com/en/dev/internals/deprecation/#deprecation-removed-in-2-1), the `host` parameter to `is_safe_url` was removed. This project currently passes `host` to determine the `next` url, breaking support for Django 2.1.

### PR DESCRIPTION
**Pull request by robhudson**

### CODE REVIEW

**Comment by johngian** [comment]
Hey @robhudson thanks for the PR.
It looks like we should use ``allowed_hosts`` for Django >= 2.1 instead.

Here is a fix I tried locally which looks like its working fine:
https://github.com/johngian/mozilla-django-oidc/commit/3cdb29a6fa9ba9a156cbedc8681b4ca1f8acd415

Feel free to adapt or cherry-pick the commit and squash to yours.

**Comment by robhudson** [comment]
Thanks @johngian! I updated my PR based on your suggestions. There's still 2 test failures that may be related to other changes in Django 2.1.

**Comment by robhudson** [comment]
I believe it's this from the Django 1.11 deprecation notes: `contrib.auth`’s `login()` and `logout()` function-based views are deprecated in favor of new class-based views `LoginView` and `LogoutView`.

`contrib.auth.login` is being called in the `OIDCAuthenticationCallbackView`

**Comment by johngian** [comment]
Apparently the failing tests are caused because of a feature removal in ``Django 2.1``.
https://docs.djangoproject.com/en/2.1/releases/2.1/#features-removed-in-2-1

I pushed a fix here:
https://github.com/johngian/mozilla-django-oidc/commit/0c9fdf1fd6c028e0234db0a255a91326b5ceb10a

Closing this PR after #268

**Pull request closed without merging**
