### PR TITLE
Add support for Django 3.x

### PR DESCRIPTION
**Pull request by johngian**

### CODE REVIEW

**Comment by johngian** [comment]
Fixes #334 #333

**Comment by thebenwaters** [comment]
Just wondering why this got closed?

**Comment by TCFox** [comment]
Might be because this is being worked on in #336, but that's just a guess.

**Comment by johngian** [comment]
Hey all! I tried to quickly patch the support for Django 3.x but there was ongoing work already done. This PR was closed because of #336

**Comment by TCFox** [comment]
Thanks heaps @johngian! Looking forward to the patch in #336 👍

**Pull request closed without merging**
