### PR TITLE
Support PKCE

### PR DESCRIPTION
**Pull request by bgroff**
Adjust comments

Remove .devcontainer

Default challenge method to S256

Fix base64 encoding

PKCE Unit Tests

Fix code_verifier KeyError

Test code_verifier parameter

AuthoricationRequestView test code_verifier

Replace assert_ with assertTrue

Replace all assert_ calls with assertTrue

Fix flake8 errors

Fix flake8 warnings

Test PKCE settings

Check for AssertionError rather than ValueError

Update documentation

Change AssertionError to ValueError

### CODE REVIEW

**Comment by bgroff** [comment]
@escattone This PR resolves the merge conflicts from this PR: https://github.com/mozilla/mozilla-django-oidc/pull/474 and addresses the issue raised with the unit test. It has been over a month since the last activity on @akatsoulas PR, so I thought I would surface this again.

**Review by escattone — CHANGES_REQUESTED** [review]
@bgroff It looks like you've pulled in an old version of `mozilla_django_oidc/views.py`.

**Comment by bgroff** [comment]
> @bgroff It looks like you've pulled in an old version of `mozilla_django_oidc/views.py`.

My apologies, I chose the wrong commit when performing the conflict resolution. The PR has been updated to use the correct imports.

**Comment by escattone** [comment]
@bgroff I'm going to close this in favor of #474, since that has been fixed and @akatsoulas is going to merge that early next week, but thanks for your work on this!

**Pull request closed without merging**
