### PR TITLE
Allow combining OIDCAuthenticationBackend with other backends.

### PR DESCRIPTION
**Pull request by johngian**
* Return `None` if request not available in kwargs

### CODE REVIEW

**Comment by johngian** [comment]
@willkg r?

**Comment by willkg** [comment]
Pretend I don't know much about Django auth. When would `request` not be in the args to `authenticate`?

**Comment by akatsoulas** [comment]
Please ignore the approval. I realized that @willkg has already started this after the review submission.

**Comment by willkg** [comment]
@akatsoulas I don't know much about that aspect of the Django authentication API, so if you're good with this, that's ok with me. I can look into it later today, but haven't, yet.

**Comment by johngian** [comment]
The idea is that different backends pass different args as credentials (eg. ModelBackend passes user/pass, OIDC passes a request object). In order to be able to fallback to different backends you need to be able to check if given the args, authentication returns a User. If not fallback to next available backend.

**Pull request merged**
