### PR TITLE
Django compat

### PR DESCRIPTION
**Pull request by jaap3**
This removes references to unsupported Django versions and backwards compatible code that is no longer required and adds Django 2.2 to the test matrices.

### CODE REVIEW

**Comment by jaap3** [comment]
I considered removing Django 2.0 and Python 3.4 from the test matrices as Django 2.0 is no longer supported by the Django project. Let me know if that's something you want.

**Comment by jaap3** [comment]
@johngian if you have any time, would you mind taking a look at this?

**Comment by akatsoulas** [comment]
Thanks @jaap3 for this PR. I had a quick look at this and I don't see anything that stands out. I will do a more thorough review this week. :+1:

**Comment by jaap3** [comment]
I've now added Django 3.0 support as well.

There's a bunch of `RemovedInDjango40Warning: smart_text() is deprecated in favor of smart_str().` warnings. However, I believe it's not safe to replace `smart_text` with `smart_str` as long as Django 1.11 / Python 2.7 is still supported

**Comment by jaap3** [comment]
The Travis failure is not caused by this PR but by some hiccup in the network connection, please rerun the failed job.

**Comment by jaap3** [comment]
Any chance you could take a look at this? `mozilla-django-oidc` is currently blocking us from upgrading to Django 3.0

**Comment by johngian** [comment]
@jaap3 i was going through the Django 3x blocking issues. I am currently reviewing this one. Thanks for the contribution :rocket:

**Comment by johngian** [comment]
> The Travis failure is not caused by this PR but by some hiccup in the network connection, please rerun the failed job.

**Comment by johngian** [comment]
This PR breaks Circle CI builds. Closing this one and added some fixes here #336

**Pull request closed without merging**
