### PR TITLE
The logout request object is passed to the OIDC_OP_LOGOUT_URL_METHOD

### PR DESCRIPTION
**Pull request by GermanoGuerrini**
This way, the method can use various parts of the request (mostly the session) to build the logout url.
For example, my idp requires the id token and that can be retrieved from the session attached to the request.

### CODE REVIEW

**Comment by peterbe** [comment]
I think this is correct @GermanoGuerrini but the patch needs a unit test. Do you think you can find a way to put one in?

**Comment by johnpaulett** [comment]
@peterbe & @GermanoGuerrini Adjusted the existing OIDC_OP_LOGOUT_URL_METHOD test case to demonstrate that the HttpRequest is passed into the function.  Let me know if you have thoughts / comments, as this is PR would be extremely helpful for me.

**Comment by johnpaulett** [comment]
Any review notes for this PR @peterbe?

**Comment by peterbe** [comment]
@johnpaulett Can you make a new PR in your name that combines the changes of this PR and your changes to the tests?

**Comment by peterbe** [comment]
Also, sorry for late reply. I must have completely missed the notification.

**Comment by johnpaulett** [comment]
@peterbe no worries! I know how tough it is maintaining projects.  Appreciate the work you and the team have done! 

New PR at mozilla/mozilla-django-oidc#216

**Comment by peterbe** [comment]
In https://github.com/mozilla/mozilla-django-oidc/pull/216 @johnpaulett took this code, added a test and rebased it up against master. And that has landed now. 

Thank you @GermanoGuerrini !

**Pull request closed without merging**
