### PR TITLE
Use jwks endpoint

### PR DESCRIPTION
**Pull request by GermanoGuerrini**
I have implemented a mechanism to improve RS256 token verification by using a possible JWKS provider endpoint as an alternative to hardcoded signing key.
I'm not fully satisfied by the tests which mock way to much of the process.
Yet, I'm using it in production and so far no problems.

### CODE REVIEW

**Comment by tpazderka** [comment]
Using https://github.com/getsentry/responses in tests would remove the need for the extensive patching of the network communication.

**Comment by peterbe** [comment]
@johngian and @akatsoulas Can you take a look at this and move it forward? 
I'm not sure who originally worked on the key verification stuff. Perhaps @willkg has experience on that part?

**Comment by willkg** [comment]
> Perhaps @willkg has experience on that part?

I don't. Sorry!

**Comment by GermanoGuerrini** [comment]
Sorry but if the issue is to refactor the tests to use getsentry, I'm quite
busy at the moment to look into it. I might have more time later this month.

**Comment by johngian** [comment]
Closing this one after #229. Thanks @GermanoGuerrini for the contribution. Regarding the testing part I am enhancing the e2e tests to include an environment based on JWKS.

:rocket:

**Pull request closed without merging**
