### PR TITLE
Renew `oidc_login_next` after user login

### LINKED ISSUE #224: OIDCAuthenticationCallbackView.success_url ignores session value
Because `OIDCAuthenticationCallbackView.success_url` is called only after `auth.login`, the session is already cycled and user is redirected according to settings instead of URL stored session.

### PR DESCRIPTION
**Pull request by tpazderka**
Close #224

### CODE REVIEW

**Comment by dmptrluke** [comment]
Is there any way this can be merged? I'm having to keep a fork for this bug fix.

**Comment by TCFox** [comment]
Still eagerly awaiting this fix, as it's causing a number of headaches. There's a fork being maintained for this fix at https://github.com/dmptrluke/mozilla-django-oidc ([diff](https://github.com/mozilla/mozilla-django-oidc/compare/master...dmptrluke:master)) but I would love to see this resolved here as it would make a lot of things easier.

Is there anything I can offer to assist with merging this PR?

**Comment by akatsoulas** [comment]
I am not sure I completely understand this patch. My understanding is that the goal of this PR is to allow some custom logic to populate the `oidc_login_next` variable. If this is the case, wouldn't overriding the `success_url` suffice in this case?

This is a long standing PR and the logic has changed a bit since this was opened. I am closing this, mainly because of the reason I gave upon. Please do reopen if this is not case.

**Comment by akatsoulas** [comment]
Following up on this, the only case that the data in the `oidc_login_next` can be overridden is in the `get_next_url`. Is this the actual problem? Having a hook for a custom `get_next_url` method could solve for this.

**Comment by mariadb-BryanAlsdorf** [comment]
Not the author, but this is a bug fix to handle users not being redirect to their original destination under certain circumstances.

When calling `auth.login(self.request, self.user)`, in some circumstances [django resets the session for security purposes](https://github.com/django/django/blob/main/django/contrib/auth/__init__.py#L106).

With the session reset, `oidc_login_next` (set it https://github.com/mozilla/mozilla-django-oidc/blob/master/mozilla_django_oidc/middleware.py#L161) is no longer available so the user is not redirected back to the original destination.

It has been a while since I had to work around this, but the main circumstance that trigger this was when the end user logs out and then logs back in with an active session. I also believe it can be triggered when the OP and RP have different session lengths, but I don't recall all the specifics off hand.

**Comment by akatsoulas** [comment]
Thank you both @mariadb-BryanAlsdorf @tpazderka . I was mainly confused by the issue that was focusing on the login process and I completely missed the middleware.

**Pull request closed without merging**
