### PR TITLE
Add test settings in Sphinx conf.

### PR DESCRIPTION
**Pull request by akatsoulas**
* Fix warnings in documentation build.

### CODE REVIEW

**Comment by akatsoulas** [comment]
@peterbe r?

**Comment by peterbe** [comment]
When I run `make docs` I get these files left over:
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/modules.rst
	docs/mozilla_django_oidc.rst

```

There is also a warning:

```
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.7.1
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 8 source files that are out of date
updating environment: 8 added, 0 changed, 0 removed
reading sources... [100%] settings
looking for now-outdated files... none found
pickling environment... done
checking consistency... /Users/peterbe/dev/DJANGO/mozilla-django-oidc/docs/modules.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] settings
generating indices... genindex py-modindex
highlighting module code... [100%] mozilla_django_oidc.views
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 1 warnings.
```

What are those extra files that get created?

**Comment by akatsoulas** [comment]
The `make docs` was the default option that was added by the cookiecutter. This calls the sphinx-autodoc [0] to automatically generate documentation from docstrings. I added a second commit just for demonstration. The generated documentation will go in the docs/source documentation and it is included in the `index.rst`. If we are interested in a feature like this we can add the source directory in gitignore and have it generated by readthedocs.

[0] http://www.sphinx-doc.org/en/stable/ext/autodoc.html#module-sphinx.ext.autodoc

**Comment by peterbe** [comment]
Do we need to add `docs/source/` to `.gitignore`?

Now I get this:

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	docs/source/
```

**Comment by akatsoulas** [comment]
Yes if we want to keep the autodoc feature, we should add this in gitignore and have this populated in readthedocs (or at least that's what I understood by doing a quick research). I guess my main question is whether we want the autodoc feature. 
For me it's definitely a nice feature. It will require to update the docstrings in the code and better document them but it should be a low effort task. Thoughts?

**Comment by peterbe** [comment]
Yeah, autodoc seems like a nice to have. I don't know what it takes to get it to work in readthedocs. 

As long as it's possible to generate the docs, that the look and work on readthedocs and that I don't have to manually run `rm some/file` after `make docs` then I'm not too bothered by the details.

**Pull request merged**
