### PR TITLE
PKCE Support

### LINKED ISSUE #397: Code authorization flow with PKCE
Could support for Code authorization flow with PKCE be added to mozilla-django-oidc ? or does that go against design priciple "Mainly support OIDC authorization code flow"`?

### PR DESCRIPTION
**Pull request by themooer1**
Added support for PKCE as defined in [rfc7636](https://datatracker.ietf.org/doc/html/rfc7636).  Resolves #397.

PKCE is enabled by default and can be controlled with these new settings:

- `OIDC_USE_PKCE` (default: `True`)
- `OIDC_PKCE_CODE_CHALLENGE_METHOD` (default:`S256`)
- `OIDC_PKCE_CODE_VERIFIER_SIZE` (default: `64`)

The above settings are documented in [settings.rst](https://github.com/themooer1/mozilla-django-oidc/edit/pkce/docs/settings.rst#L267)

Tests were added to [test_utils.py](https://github.com/themooer1/mozilla-django-oidc/blob/pkce/tests/test_utils.py#L54) and [test_views.py](https://github.com/themooer1/mozilla-django-oidc/blob/pkce/tests/test_views.py), and PKCE was shown working using Google as an OP.

According to [rfc6749#section-3.1](https://datatracker.ietf.org/doc/html/rfc6749#section-3.1) and [rfc6749#section-3.2](https://datatracker.ietf.org/doc/html/rfc6749#section-3.2), the authorization and token endpoints must ignore unrecognized parameters, so PKCE is backwards compatible with OAuth 2.0 servers, and is, therefore, safe to enable by default.  In [OAuth 2.1](https://oauth.net/2.1/) PKCE is required.

Because it's backwards compatible, this pull request includes a minor version bump to `2.1.0`.

### CODE REVIEW

**Comment by Phill93** [comment]
Can someone please review and merge this?

**Comment by jcriddle-nci** [comment]
Is anyone from the team planning on reviewing and merging this PR in?

**Comment by mooreds** [comment]
Would love to see this merged.

**Comment by akatsoulas** [comment]
Closing this in favor of #474. It's the same exactly PR rebased on `main` and all the commits are squashed into one. The only new addition is the second commit which fixes a single failing test. I will start the review process and add any comments in PR #474.

**Pull request closed without merging**
