### PR TITLE
Update docs for running tests

### LINKED ISSUE #110: update contribution docs
After we landed the `tox` changes, we updated the README, but didn't update the contribution docs:

https://mozilla-django-oidc.readthedocs.io/en/latest/contributing.html#tips

### PR DESCRIPTION
**Pull request by willkg**
Fixes #110

### CODE REVIEW

**Comment by willkg** [comment]
For some reason, my editor also removed trailing whitespace. Sorry about the noise that caused.

**Comment by willkg** [comment]
Can someone merge this?

**Comment by johngian** [comment]
I forgot to merge that after approving :\

**Comment by willkg** [comment]
No worries! Thank you!

**Pull request merged**
