### PR TITLE
Automatic client configuration

### PR DESCRIPTION
**Pull request by pc9795**
Users will now able to use metadata response for automatic configuration using metadata endpoint and turn in on and off also. I have added relevant test cases and linting. In the 'Contributing' document it was written to update documentation in History.rst and Readme.rst. But I think History.rst contains change log for a version and Readme.rst  doesn't contain any feature list. So I am not clear about where to put the documentation.

### CODE REVIEW

**Comment by pc9795** [comment]
closes #280

**Comment by johngian** [comment]
Hey @pc9795 thank you for the contribution :rocket: 
Here are some high level comments about the PR:

* It looks like every time we need to access anything related to the OIDC endpoint, we query the metadata endpoint.
  * Maybe adding some caching would be a good idea. Imagine a service with a lot of users. By adding metadata discovery you increase by 2x the amount of HTTP requests for the OIDC flow
* We also have the ``get_settings`` methods that you could move this logic to decouple the OIDC flow with the client configuration
* Please add some docs to explain how OIDC discovery works and what the new config entry does.

**Comment by pc9795** [comment]
@johngian  Thanks for reviewing, I will work on your suggested improvements.

**Comment by pc9795** [comment]
@johngian took action on code review comments.

**Comment by pc9795** [comment]
Hi @johngian, does anything else is required?

**Comment by pc9795** [comment]
Hi @johngian  I have implemented suggested changes.

**Comment by mihow** [comment]
Are there plans to merge this soon?

**Comment by davidjb** [comment]
Any updates on merging?

**Comment by nessita** [comment]
Hi all, thanks for working on this, any chance it gets merged?

**Comment by n0emis** [comment]
Is there any chance that we could get this PR merged sometime?

**Pull request closed without merging**
